---
title: "BLOCK 1 Formative Submission"
params: 
    SHOW_SOLS: FALSE
    TOGGLE: TRUE
format: html
---

```{r}
#| include: false
library(tidyverse)
source('assets/dropdowns.R')
source('assets/setup.R')
file.copy("block1_formative.R","../docs/2627/formatives/block1_formative.R")
```

:::frame

Download <a href="../formatives/block1_formative.R" download="block1_formative.R">this .R script</a>, and copy your answers from the last few weeks into it in the appropriate places.  

Then submit it on Learn.. 

:::




| Skill | Question |
| ----- | -------- |
| C1: I can manage libraries/packages in R.      | From [week 1](01ex.html), submit Question 1 |
| C2: I can modify the arguments of a given R function to arrive at the desired output. | From [week 2](02ex.html), submit Question 3 |
| V2: I can appropriately plot associations between two variables. | From [week 3](03ex.html), submit Question 4 |
| S2: I can compute appropriate measure(s) of dispersion for a given variable. | From [week 3](03ex.html), submit Question 5 |
| C4: I can extract specific subsets of a given dataset. | From [week 4](04ex.html), submit Question 2 |
| S1: I can compute appropriate measure(s) of association for a given pair of variables. | From [week 5](05ex.html), submit Question 3 |